spring.application.name=food-order-system


spring.datasource.url=jdbc:mysql://localhost:3306/food_ordering_system
spring.datasource.username=aldora
spring.datasource.password=14@Rolivhuwa#2001

#hibernate use dialect to create my sql statements
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#tells hibernate to automatically create DB tables and if thereare changesin DB it will update the DB
spring.jpa.hibernate.ddl-auto=update